server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDR}

variables:
    TRACKER_PORT : ${TRACKER_PORT}

    KAFKA_BROKER: ${KAFKA_BROKER}
    GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA}

    RAW_GPS_LOCATION_TOPIC_DEV: ${RAW_GPS_LOCATION_TOPIC_DEV}
    RAW_GPS_LOCATION_TOPIC_PROD: ${RAW_GPS_LOCATION_TOPIC_PROD}